### ISSUE TITLE
Having problems when using in a workflow

### ISSUE THREAD

**Issue by jpw1991** [BepInEx/BepInEx.AssemblyPublicizer#11]
Hello there,

I've used this tool for a long time and it works great. But I'm getting some issues trying to use it in workflows:

1. I had to change/fix a condition like [this](https://github.com/jpw1991/chebs-necromancy/commit/53c8bf8eaf683effecb5960f19abfe2179e0c0d6). Someone else also encountered this earlier (discord link [here](https://discord.com/channels/829466376875933756/829469098936631346/1180525060965011526))
2. I have a problem where it doesn't seem to be publicizing [here](https://github.com/jpw1991/chebs-necromancy/actions/runs/7561792999)

Any idea what's wrong in the workflow?

Thank you

**Comment by jpw1991** [comment]
I was able to get it to work by manually publicizing like this:

```yml
      - name: Install dependencies
        run: |
          mkdir packages
          dotnet restore
          nuget restore -PackagesDirectory packages ${{env.name}}/packages.config
          dotnet tool restore
          # uncomment below and remove "Manually publicize" step once this is resolved: https://github.com/BepInEx/BepInEx.AssemblyPublicizer/issues/11
          #dotnet build --configuration Release --no-restore
      
      - name: Manually publicize and build
        run: |
          # as described above in "Install dependencies": remove entire step once that issue is resolved
          dotnet tool install -g BepInEx.AssemblyPublicizer.Cli
          assembly-publicizer --overwrite ${{env.valheiminstalldir}}/valheim_Data/Managed/assembly_valheim.dll
          dotnet build --configuration Release --no-restore
```

Working workflow [here](https://github.com/jpw1991/chebs-necromancy/actions/runs/7566916751/job/20605095182), but I'd still like help getting the dynamic publicization to work in my workflow instead.
